---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 17/06/2024 23:06
---
LobbyGlobalOptions = {
    {
        default = 1,
        label = "M27 Teams",
        help = "Which teams should M27 apply to?",
        key = "M27Teams",
        pref = 'lob_teams_combo',
        type = 'index', --'edit',
        --valid = '^%d+$',
        values = {
            {
                text = "None and odd",
                help = "Apply to odd teams and all AI with no team",
                key = 1,
            },
            {
                text = "All",
                help = "Apply to all AI",
                key = 2,
            },
        },
    },
}