---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 16/06/2024 20:23
---

--WARNING: CURRENTLY THE BELOW DOESNT TRIGGER, MAYBE LOUD DOESNT USE AIBRAINS DESPITE HAVING SOME CODE FOR THEM? OR THERE'S AN ERROR WITH MY HOOK ATTEMPT
local StandardBrain = moho.aibrain_methods
local M27Map = import('/mods/Mini27AI/lua/AI/M27Map.lua')
local M27ParentDetails = import('/mods/Mini27AI/lua/AI/M27ParentDetails.lua')


NewAIBrain = Class(StandardBrain) {
    --Currently this is only used to flag that the aiBrain uses this logic, and to make sure the navigational mesh gets generated; OnBeginSession and OnDefeat left in for reference in case they are wanted in the future to also run this AI's custom code
    OnBeginSession = function(self)
        M27ParentDetails.BrainBeginSession(self)
        StandardBrain.OnBeginSession(self)
        LOG('OnBeginSession started for brain '..(self.Nickname or 'nil'))
    end,

    OnDefeat = function(self)
        StandardBrain.OnDefeat(self)
    end,

    OnCreateAI = function(self, planName)
        StandardBrain.OnCreateAI(self)
        self.Mini27AI = true
        ForkThread(M27Map.SetupMap, self)
        LOG('OnCreateAI started for brain '..(self.Nickname or 'nil'))
    end,

}