---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:56
---
local M27Units = import('/mods/Mini27AI/lua/AI/M27Units.lua')

do --Per Balthazaar - encasing the code in do .... end means that you dont have to worry about using unique variables
    local M27OldUnit = Unit
    Unit = Class(M27OldUnit) {
        OnCreate = function(self)
            M27OldUnit.OnCreate(self)
            ForkThread(M27Units.OnCreate, self)
        end,
        OnStopBuild = function(self, unit)
            if unit and not(unit.Dead) and unit.GetFractionComplete and unit:GetFractionComplete() == 1 then
                ForkThread(M27Units.OnConstructed, self, unit)
            end
            return M27OldUnit.OnStopBuild(self, unit)
        end,
        OnDamage = function(self, instigator, amount, vector, damageType)
            M27OldUnit.OnDamage(self, instigator, amount, vector, damageType)
            M27Units.OnDamaged(self, instigator) --Want this after just incase our code messes things up
        end,
        OnKilled = function(self, instigator, type, overkillRatio) --NOTE: For some reason this doesnt run a lot of the time; onkilledunit is more reliable
            M27Units.OnUnitDeath(self)
            M27OldUnit.OnKilled(self, instigator, type, overkillRatio)
        end,
        OnReclaimed = function(self, reclaimer)
            M27Units.OnUnitDeath(self)
            M27OldUnit.OnReclaimed(self, reclaimer)
        end,
        OnDecayed = function(self)
            --LOG('OnDecayed: Time='..GetGameTimeSeconds()..'; self.UnitId='..(self.UnitId or 'nil'))
            M27Units.OnUnitDeath(self)
            M27OldUnit.OnDecayed(self)
        end,
        OnKilledUnit = function(self, unitKilled, massKilled)
            M27Units.OnUnitDeath(unitKilled)
            M27OldUnit.OnKilledUnit(self, unitKilled, massKilled)
        end,
        OnDestroy = function(self)
            --LOG('OnDestroy: Time='..GetGameTimeSeconds()..'; self.UnitId='..(self.UnitId or 'nil'))
            M27Units.OnUnitDeath(self)
            M27OldUnit.OnDestroy(self)
        end,
    }
end