---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:34
---
local M27Brain = import('/mods/Mini27AI/lua/AI/M27Brain.lua')
keyToBrain = keyToBrain or { }
keyToBrain['mini27ai'] = M27Brain.NewAIBrain -- <- make sure import path points to the brain instance
keyToBrain['miniaicheat'] = M27Brain.NewAIBrain -- <- make sure import path points to the brain instance