---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:24
---
local StandardBrain = import("/lua/aibrain.lua").AIBrain
local M27Map = import('/mods/Mini27AI/lua/AI/M27Map.lua')

NewAIBrain = Class(StandardBrain) {

    OnBeginSession = function(self)
        StandardBrain.OnBeginSession(self)
    end,

    OnDefeat = function(self)
        StandardBrain.OnDefeat(self)
    end,

    OnCreateAI = function(self, planName)
        StandardBrain.OnCreateAI(self)
        self.Mini27AI = true
        ForkThread(M27Map.SetupMap, self)
    end,
}