---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:28
---
local NavUtils = import("/lua/sim/navutils.lua")

bMapSetupRun = false

function SetupMap(aiBrain)
    if not(bMapSetupRun) then
        bMapSetupRun = true
        if not(NavUtils.IsGenerated()) then
            NavUtils.Generate()
        end
    end
    --LOG('M27Temp setup') --Remove comments if wanting to confirm code is running
end
