---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by maudlin27.
--- DateTime: 08/05/2024 22:21
---

Tooltips = {
    aitype_mini27ai = {
        title = "<LOC M27_0001>AI: Mini27",
        description = "<LOC M28_0002>Simple AI for AI developers to use as a starting point",
    },
    aitype_miniaicheat = {
        title = "<LOC M27_0003>AIx: Mini27",
        description = "<LOC M28_0002>Cheating simple AI for AI developers to use as a starting point",
    },
}
